### PR TITLE
add <= and >=

### PR DESCRIPTION
**Pull request by gilesbradshaw**
just make it easier to do

````
{browser.lessThanOrEqual.medium && <div>medium or below</div>}
{browser.greaterThan.medium && <div>above medium</div>}

```

without having to remember the next one up

### CODE REVIEW

**Comment by gilesbradshaw** [comment]
(probably shouldn't have added the build directory)

**Comment by AlecAivazis** [comment]
yea, if you don't mind removing `build` from the PR i would love to merge this

**Comment by gilesbradshaw** [comment]
There you go

**Comment by AlecAivazis** [comment]
Thanks! I'll merge once I get the 👍 from travis

**Comment by AlecAivazis** [comment]
Should be published now. Thanks again for the contribution @gilesbradshaw!

**Comment by AlecAivazis** [comment]
So apparently I need to spend some more time thinking about PRs when staying up late.

it just occurred to me the use case you originally suggested could be accomplished with the original API - albeit a bit verbosely: `browser.lessThan.medium && browser.equalTo.medium`. The "old" way causes half as many calculations on resize, allowing for increased performance at a very sketchy time for the browser so it might be worth giving up a slight amount of dev experience...

**Comment by AlecAivazis** [comment]
I suppose, now that I think about it some more (sorry for the sleepy brain dump) - I would get very annoyed having to repeat that pattern so often. I might want to increase the default throttle time once I can spend some time testing the performance.

Regardless, I'll keep it for now and if someone complains I'll probably tag you to chime in if that's okay :smile:

**Comment by gilesbradshaw** [comment]
ah yes good point

**Comment by gilesbradshaw** [comment]
ah ok for ref I think what you mean is 

    browser.greaterThan.medium || browser.mediaType === 'medium'

(there is no equalTo.medium)

**Pull request merged**
