### PR TITLE
Add param to configure infinity media type

### LINKED ISSUE #46: replace "infinity" with a maximum value
Hey,

I was just wondering if there was anyway to replace the infinity key/value with a maximum of a sort, as i am currently using mediaType to define which size of image loads (small, medium, large) but when the window scale is beyond large it goes to infinity...

Any Help would be Greatly Appreciated.

### PR DESCRIPTION
**Pull request by xuopled**
If I can customize my breakpoints names, I want to customize my `infinity` query name : 

For exemple : 

```
browser: createResponsiveStateReducer({
      s: 768,
      m: 992,
      l: 1200,
}, "xl"),
```

Fix #46

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Thanks for writing this up @xuopled! The code looks fine but I want to do some testing around conflicting breakpoints. Hopefully I can get around it this weekend.

**Comment by xuopled** [comment]
Your are welcome. I update the first comment to add an example

**Comment by AlecAivazis** [comment]
Alright, i'm going to merge this - thanks again @xuopled!

**Comment by xuopled** [comment]
Perfect ! Thank you

**Pull request merged**
